### PR TITLE
Matt tweaks

### PR DESCRIPTION
**Pull request by maphew**
mostly doc updates

### CODE REVIEW

**Review by tibold — APPROVED** [review]

**Comment by tibold** [comment]
@maphew , my Qt folder is only 2.5 GB. :)

**Comment by GitMensch** [comment]
qt4.8.1: 629MB :-)

**Comment by GitMensch** [comment]
@tibold as it is already approved I suggest to accept the PR - or do you want @maphew to adjust the size before?

**Comment by tibold** [comment]
Sorry got distracted and forgot to press the button. ^_^

**Comment by maphew** [comment]
@GitMensch only 2.5 for Qt? Then I definitely want to know how. Please review the Dev Build environment in the readme and let me know if you see anything over-specified. 

It took a lot of trial and error to get to a working state. I wouldn't be suprised if the large size of mine is because of incomplete uninstalls.

**Comment by tibold** [comment]
@maphew I'd suggest to check on the installed components in the Qt maintenance tool. Maybe there is something extra selected there?

Here's what I have:
image

**Comment by GitMensch** [comment]
Nokia Qt SDK Version 1.2.1
=> 630 MB + 100 MB for QtCreator; + easily found when searching for its file name: "[QtSdk-offline-win-x86-v1_2_1.exe](https://duckduckgo.com/?q=QtSdk-offline-win-x86-v1_2_1.exe)" - I think it was the last one from Nokia, shipping with QT 4.8.1

**Pull request merged**
