### PR TITLE
Release of v1.0.0

### PR DESCRIPTION
**Pull request by tibold**
Cleaned up the code base a bit and applied default formatting from QtCreator.

Automated the build process using a ps1 script. To use it simply do:
```
pwsh.exe -Command .\deployment\Build.ps1 -verbose
```
from the repository root.

> The script was tested using __Powershell Core 6.2__. It might work with previous versions, but if not please use `choco install pwsh` to get v6.2.

Additionally the `Build.ps1` script accepts an `-Architecture` parameter to build either `x64` or `x86`.

---

All build files and artifacts are placed under the `var/` folder, installers you can find under the `var/installers`. The installer has been renamed to `svg_explorer_extension_{#arch}.exe`

---

This should be enough to get the project working again. I am still looking for a code signing certificate, but in the meantime the installers produced should be functional enough to provide a working update over the old installers, with up to date dependencies and stuff.

---

I have not yet touched the CI setup, but it should be quite straight forward to use the provided build script.

### CODE REVIEW

**Comment by tibold** [comment]
@maphew, would you mind taking the changes for a spin? :)
Eg. try the build scripts and see if the produced installers are functional. 

Thanks!

**Comment by tibold** [comment]
Also I'm unsure about the version number. I've seen a few numbers here and there, but was nothing among the releases. :)

**Comment by maphew** [comment]
..taking for a spin this afternoon.

Appveyor builds were called 1.0.x but only had one "release" that lasted a couple of days. Started with 1 because I had trouble getting 0-based v to work initially. Probably few to none would be affected if you decide v0.2 is next release number. (I vote for v1 myself. We're at a significant milestone in the project :-)

**Comment by maphew** [comment]
My vcvarsall.bat is in a different location. This might mean I don't have the right version of Visual Studio? After changing the path in utils.psm (and `choco install innosetup`) build ran until _"VERBOSE: LINK : fatal error LNK1104: cannot open file 'msvcprt.lib'"_. Full output attached.

[build-report-mhw-2019-12-29.txt](https://github.com/tibold/svg-explorer-extension/files/4008503/build-report-mhw-2019-12-29.txt)

My path:

`$environmentSetupBatchFile = "c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"`

**Comment by tibold** [comment]
What VS do you have installed or how did you install it?
I plan to standardise the environment with a script and chocolatey but in the meantime it might be a little different.
I just used the 2017 and 2019 community installer. It is what I use daily actually.

**Comment by maphew** [comment]
VS 2017. https://github.com/tibold/svg-explorer-extension/blob/develop/README.md#developer-build-environment-c2019 has the broad strokes of my dev environment, though the description there is a lot cleaner than how I arrived at it. Rereading it, I now remember I've only installed Build Tools (trying to keep space usage down). I tried adding `choco install visualstudio2017community` today but build still fails. 

A new "Community" folder showed up under "C:\Program Files (x86)\Microsoft Visual Studio\2017", but not a new `vcvarsall.bat`.

This is what I get with unmodified Utils.psm:
~~~
$ pwsh.exe -Command .\deployment\Build.ps1 -verbose
VERBOSE: Loading module from path 'D:\code-maphew\svg-explorer-extension\deployment\Utils.psm1'.
VERBOSE: Exporting function 'Assert-LastExitCode'.
VERBOSE: Exporting function 'Invoke-Batch'.
VERBOSE: Exporting function 'Use-VisualStudioBuildTools'.
VERBOSE: Exporting function 'Use-QtBuildTools'.
VERBOSE: Exporting function 'Use-InnoSetup'.
VERBOSE: Importing function 'Assert-LastExitCode'.
VERBOSE: Importing function 'Invoke-Batch'.
VERBOSE: Importing function 'Use-InnoSetup'.
VERBOSE: Importing function 'Use-QtBuildTools'.
VERBOSE: Importing function 'Use-VisualStudioBuildTools'.
VERBOSE: Setting up development environment.
Requested Visual Studio version 2017 or edition Community is not installed
At D:\code-maphew\svg-explorer-extension\deployment\Utils.psm1:55 char:9
+         throw "Requested Visual Studio version $Version or edition $E ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Requested Visual St\u2026ty is not installed:String) [], RuntimeException
+ FullyQualifiedErrorId : Requested Visual Studio version 2017 or edition Community is not installed
~~~

~~~
# dir /s/b v*.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsMSBuildCmd.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd\core\vsdevcmd_end.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd\core\vsdevcmd_start.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd\ext\vcvars.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\vsdevcmd\ext\vcvars\vcvars140.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars32.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsamd64_x86.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsx86_amd64.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd\core\vsdevcmd_end.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd\core\vsdevcmd_start.bat
~~~

I'll try again with Chocolatey's 2019 Community edition of VS but it might be a day or two.

**Comment by tibold** [comment]
Oki, I’ll try out the choco based install and see what it does. I haven’t used it before. I needed full VS before. :)

Tibold Kandrai
Software Architect & Engineer
________________________________

**Comment by tibold** [comment]
Found the problem:
```
[ERROR:vcvars.bat] Spectre is not installed for 'c++' verify compatibility for '' with spectre
```

Now for the solution...

**Comment by tibold** [comment]
@maphew, I think I figured out how to make it work. :)

---

I have updated the `Utils.psm1` to treat the `BuildTools` as another Visual Studio edition. Additionally I pulled these options out to the `Build.ps1`, so one can pick what should be used, such as:
```
pwsh.exe -Command .\deployment\Build.ps1 -VSEdition BuildTools -Verbose
```

---

The compile error was due to missing Spectre mitigated libraries. I got them installed using the follow steps:
* First I uninstalled the build tools and the vtools workload. I am not certain that all has to be uninstalled, but I kept getting errors unless I did it.
```
choco uninstall visualstudio2017-workload-vctools
choco uninstall visualstudio2017buildtools
```
* Reboot the computer. After uninstall, I could not re-install anything until a reboot...
* Reinstall both packages:
```
choco install visualstudio2017buildtools
choco install visualstudio2017-workload-vctools --params "--add Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre"
```

The extra component in the vctools workload is what was causing the issues.

**Comment by maphew** [comment]
Initially I `git pull`ed and ran `build.cmd` just to see what would happen. It errored out which didn't surprise me but the message had some weird codes in it which make me think there might be a unicode mismatch or something: note `Visual St\u2026ty ` instead of `Visual Studio`. I'm running the script from CMD shell via [ConEmu](https://conemu.github.io/), so this might be coming from outside SVG explorer extension.

~~~
VERBOSE: Setting up development environment.
Requested Visual Studio version 2017 or edition Community is not installed
At D:\code-maphew\svg-explorer-extension\deployment\Utils.psm1:53 char:9
+         throw "Requested Visual Studio version $Version or edition $E ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Requested Visual St\u2026ty is not installed:String) [], RuntimeException
+ FullyQualifiedErrorId : Requested Visual Studio version 2017 or edition Community is not installed
~~~

about to try uninstalling and reinstalling vctools...

**Comment by maphew** [comment]
Powershell doesn't have the escaped string wierdness:
~~~
Requested Visual Studio version 2017 or edition Community is not installed
At D:\code-maphew\svg-explorer-extension\deployment\Utils.psm1:53 char:9
+         throw "Requested Visual Studio version $Version or edition $E ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Requested Visua...s not installed:String) [], RuntimeException
    + FullyQualifiedErrorId : Requested Visual Studio version 2017 or edition Community is not installed
~~~

----
Uninstalled and reinstalled using the commands from above. After that using build command with Buildtools parameter was successful, **and** the installer worked (though while uninstalling the currrently installed version there was that regservr error), **and** preview works, including compressed svg. **Alright!**

**Review by maphew — APPROVED** [review]

**Comment by tibold** [comment]
Thanks for testing.

I missed the `build.cmd` file. :)
Please keep all build and deployment related scripts in the `./deployment/` folder.

---

I have set the version number to `v1.0.0`.

**Pull request merged**
